### ISSUE TITLE
Migration fails

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued-skeleton#24]
https://github.com/vaizard/glued-skeleton/blob/2cab81090614895d2629a872c650158ddee7cd60/glued/Core/Install/Migrations/20200413094139_worklog_initial.php#L73

fails with 

```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'c_stor_name'; check that column/key exists in /var/www/html/glued-skeleton/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:185
Stack trace:
#0 /var/www/html/glued-skeleton/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(185): PDO->exec()
#1 /var/www/html/glued-skeleton/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(160): Phinx\Db\Adapter\PdoAdapter->execute()
#2 /var/www/html/glued-skeleton/vendor/robmorgan/phinx/src/Phinx/Migration/AbstractMigration.php(198): Phinx\Db\Adapter\AdapterWrapper->execute()
#3 /var/www/html/glued-skeleton/glued/Core/Install/Migrations/20200413094139_worklog_initial.php(73): Phinx\Migration\AbstractMigration->execute()
#4 /var/www/html/glued-skeleton/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(109): WorklogInitial->change()
#5 /var/www/html/glued-skeleton/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(377): Phinx\Migration\Manager\Environment->executeMigration()
#6 /var/www/html/glued-skeleton/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(350): Phinx\Migration\Manager->executeMigration()
#7 /var/www/html/glued-skeleton/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate()
#8 /var/www/html/glued-skeleton/vendor/symfony/console/Command/Command.php(255): Phinx\Console\Command\Migrate->execute()
#9 /var/www/html/glued-skeleton/vendor/symfony/console/Application.php(912): Symfony\Component\Console\Command\Command->run()
#10 /var/www/html/glued-skeleton/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/html/glued-skeleton/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun()
#12 /var/www/html/glued-skeleton/vendor/symfony/console/Application.php(140): Phinx\Console\PhinxApplication->doRun()
#13 /var/www/html/glued-skeleton/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#14 {main}
Script php vendor/bin/phinx migrate -e production handling the post-update-cmd event returned with error code 1
```

must have the column first to be able to drop it! doh.

**Comment by pohadkar** [comment]
posledni pokus, worklog initials uz prosel a seklo se to dale
http://prntscr.com/s5vre9

**Comment by killua-eu** [comment]
resolved with https://github.com/vaizard/glued-skeleton/commit/77e3b4939906edd149100d9e8f1ddcb0a6e8172e
